### ISSUE TITLE
assembly

### ISSUE THREAD

**Issue by trolljoe** [Ast3risk-ops/example-files#2]
add .asm

**Comment by Ast3risk-ops** [comment]
Did you know you can make [pull requests](../pulls)?

**Comment by Ast3risk-ops** [comment]
Done (https://github.com/Ast3risk-ops/example-files/commit/ddcd08a47c16c2ede53872f0acbb24339a592fc0)

**Comment by trolljoe** [comment]
> Did you know you can make [pull requests](../pulls)?

i dont wanna
